openapi: 3.0.0
info:
  title: Campfire Store API
  version: 1.0.0
servers:
  - url: http://{{url}}
tags:
  - name: products
paths:
  /api/v1/products:
    get:
      tags:
        - products
      summary: get all products
      description: >-
        Get list of multiple items of the type product. The results can be
        filtered, sorted, paginated and limited using specific query parameters.
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - products
      summary: create product
      description: Create a new item of the type product by provided ID.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/products/{id}:
    get:
      tags:
        - products
      summary: get product
      description: Get an existing item of the type product by provided ID.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: Specifies ID of the product to search for.
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - products
      summary: update product
      description: Update an existing item of the type product by provided ID.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {}
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: Specifies ID of the product to search for.
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - products
      summary: delete product
      description: Delete an existing item of the type product by provided ID.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: Specifies ID of the product to search for.
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}