parameters:
  # Common
  language:
    name: language
    description: Session language. Default value is <code>en</code>.
    in: query
    type: string
  currency:
    name: currency
    description: Session currency. Default value is <code>USD</code>.
    in: query
    type: string
  limit:
    name: limit
    description: Maximal number of results per page. Default value is <code>25</code>, maximal is <code>50</code>.
    in: query
    type: integer
  page:
    name: page
    description: Current page number.
    in: query
    type: integer
  sort:
    name: sort
    description: Comma-separated sorting parameters.
    in: query
    type: string
  fields:
    name: fields
    description: Comma-separated set of returned fields.
    in: query
    type: string
  # Category
  categoryId:
    name: id
    description: <code>id</code> of a category to search for.
    in: path
    required: true
  # Product
  productId:
    name: id
    description: <code>id</code> of a product to search for.
    in: path
    required: true
  profuctFilter:
    name: filter
    description: JSON string with parameter names and values to filter by.<br><br>Supported query conditions&#58; <code>$gt</code>, <code>$gte</code>, <code>$lt</code>, <code>$lte</code>, <code>$in</code>, <code>$or</code>, <code>$regex</code>, etc. Find more at <a target="_blank" href="https://www.mongodb.com/docs/manual/reference/operator/query/">Query and Projection Operators</a>.<br><br>Supported value types&#58; <code>string</code>, <code>number</code>, <code>boolean</code>, <code>object</code>, <code>array</code>.<br><br>Example&#58; <code>{ "manufacturer"&#58; { "$in"&#58; ["Cube", "Canyon"] }, "priceI18n.USD"&#58; {  "$gte"&#58; 1000, "$lte"&#58; 5000 } }</code>.
    in: query
    content:
      application/json:
        schema:
          type: object
  # Title
  titleId:
    name: id
    description: <code>id</code> of a title to search for.
    in: path
    required: true
  # User
  userIdOrEmail:
    name: id
    description: <code>id</code> or <code>email</code> of a user to search for.
    in: path
    required: true
  # Cart
  cartId:
    name: cartId
    description: <code>id</code> of a cart to search for.
    in: path
    required: true
  # Order
  orderId:
    name: orderId
    description: <code>id</code> of an order to search for.
    in: path
    required: true
  # Cart/order entry
  entryId:
    name: entryId
    description: <code>id</code> of an entry to search for.
    in: path
    required: true
  # Image
  imageId:
    name: imageId
    description: <code>id</code> of an image to search for.
    in: path
    required: true
  # Photo
  photoId:
    name: photoId
    description: <code>id</code> of a photo to search for.
    in: path
    required: true
