parameters:
  # Common
  language:
    name: language
    description: Session language. Default is en.
    in: query
    type: string
  currency:
    name: currency
    description: Session currency. Default is USD.
    in: query
    type: string
  limit:
    name: limit
    description: Maximal number of results per page. Default value is 25, maximal is 50.
    in: query
    type: integer
  page:
    name: page
    description: Current page number.
    in: query
    type: integer
  sort:
    name: sort
    description: Comma-separated sorting parameters.
    in: query
    type: string
  fields:
    name: fields
    description: Comma-separated set of returned fields.
    in: query
    type: string
  # Category
  categoryId:
    name: id
    description: ID of a category to search for.
    in: path
    required: true
  # Product
  productId:
    name: id
    description: ID of a product to search for.
    in: path
    required: true
  # User
  userIdOrEmail:
    name: id
    description: ID or email of a user to search for.
    in: path
    required: true
  # Cart
  cartId:
    name: cartId
    description: ID of a cart to search for.
    in: path
    required: true
  # Order
  orderId:
    name: orderId
    description: ID of an order to search for.
    in: path
    required: true
  # Cart/order entry
  entryId:
    name: entryId
    description: ID of an entry to search for.
    in: path
    required: true
